server:
  port: 9999
spring:  
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/dbname
        username: root
        password: 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' q
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
my:
    returnPath: http://192.168.185.97:9999/
    socketUrl: ws://192.168.185.97:9999/socket
    fileSavePath: /usr/local/tomcat7/data/